# Generated by Django 6.0.5 on 2026-05-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('discount_price', models.BigIntegerField(blank=True, null=True)),
                ('main', models.ImageField(upload_to='products')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('in_stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_code', models.UUIDField(null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
    ]
