# Generated by Django 6.0.5 on 2026-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
