# Generated by Django 6.0.5 on 2026-05-26 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
