# Generated by Django 6.0.5 on 2026-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
