# Generated by Django 6.0.5 on 2026-05-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_cart_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('subtotal', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('order_status', models.CharField(choices=[('PENDING_ORDER', 'PENDING_ORDER'), ('ORDER_RECEIVED', 'ORDER_RECEIVED'), ('ORDER_CONFIRMED', 'ORDER_CONFIRMED'), ('ORDER_PROCESSED', 'ORDER_PROCESSED'), ('ORDER_SHIPPED', 'ORDER_SHIPPED'), ('ORDER_RETURNED', 'ORDER_RETURNED'), ('ORDER_DELIVERED', 'ORDER_DELIVERED')], default='PENDING_ORDER', max_length=100)),
                ('payment_method', models.CharField(choices=[('paystack', 'paystack'), ('flutterwave', 'flutterwave'), ('cash_on_delivery', 'cash_on_delivery'), ('paypal', 'paypal')], default='paystack', max_length=50)),
                ('payment_completed', models.BooleanField(default=False)),
                ('ref', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
    ]
